# Generated by Django 4.2.5 on 2023-09-15 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0003_alter_useraccount_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'user account', 'verbose_name_plural': 'Users accounts'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
