# Generated by Django 4.2.5 on 2023-09-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0004_alter_useraccount_options_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
